# Generated by Django 5.2.5 on 2025-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone (WhatsApp)')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('race_date', models.DateField(blank=True, null=True, verbose_name='Data da corrida')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('health_disclaimer', models.BooleanField(default=False, verbose_name='Declaração de saúde')),
                ('athlete_declaration', models.BooleanField(default=False, verbose_name='Declaração do atleta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Inscrição de Corrida',
                'verbose_name_plural': 'Inscrições de Corrida',
                'ordering': ['-created_at'],
            },
        ),
    ]
