# Generated by Django 5.2.5 on 2025-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_raceregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceregistration',
            name='race_date',
        ),
        migrations.AlterField(
            model_name='raceregistration',
            name='athlete_declaration',
            field=models.BooleanField(default=False, help_text='Confirma que conhece seu estado de saúde e treinou adequadamente', verbose_name='Declaração do atleta'),
        ),
        migrations.AlterField(
            model_name='raceregistration',
            name='health_disclaimer',
            field=models.BooleanField(default=False, help_text='Confirma que leu o aviso médico sobre problemas de saúde', verbose_name='Declaração de saúde'),
        ),
    ]
