# Generated by Django 5.2.5 on 2025-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_raceregistration_race_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceregistration',
            name='health_disclaimer',
        ),
        migrations.AlterField(
            model_name='raceregistration',
            name='athlete_declaration',
            field=models.BooleanField(default=False, help_text='O atleta assume e expressamente declara que é conhecedor do seu estado de saúde e capacidade atlética e que treinou adequadamente para o evento', verbose_name='Ciente'),
        ),
    ]
