# Generated by Django 5.2.5 on 2025-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_raceregistration_health_disclaimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceregistration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email de confirmação enviado'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='modality',
            field=models.CharField(choices=[('INFANTIL', 'Infantil'), ('ADULTO', 'Adulto')], default='ADULTO', help_text='Escolha entre Infantil ou Adulto', max_length=10, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='shirt_size',
            field=models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XXG', 'XXG')], default='M', help_text='Escolha o tamanho da sua camisa', max_length=3, verbose_name='Tamanho da Camisa'),
        ),
    ]
