# Generated by Django 5.2.5 on 2025-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_raceregistration_confirmation_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceregistration',
            name='shirt_size',
            field=models.CharField(default='M', help_text='Escolha o tamanho da sua camisa', max_length=3, verbose_name='Tamanho da Camisa'),
        ),
    ]
