# Generated by Django 5.2.5 on 2025-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_raceregistration_shirt_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.RemoveField(
            model_name='raceregistration',
            name='confirmation_email_sent',
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='payment_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email de confirmação de pagamento enviado'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')], default='PENDING', help_text='Status atual do pagamento da inscrição', max_length=10, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='registration_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email de confirmação de inscrição enviado'),
        ),
    ]
