# Generated by Django 5.2.5 on 2025-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_examplemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceregistration',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Pagamento'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Sessão de Checkout do Stripe'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Payment Intent do Stripe'),
        ),
    ]
