# Generated by Django 5.2.5 on 2025-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_raceregistration_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceregistration',
            name='course',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('RUN_5K', '5KM (Corrida)'), ('WALK_3K', '3KM (Caminhada)')], default='RUN_5K', help_text='Kids, 5KM (Corrida) ou 3KM (Caminhada)', max_length=10, verbose_name='Percurso'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='responsible_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='responsible_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='raceregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
