# Generated by Django 5.2.5 on 2025-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_raceregistration_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
