# Generated by Django 5.2.5 on 2025-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cpf_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceregistration',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Número único de 5 dígitos gerado quando pagamento é confirmado', max_length=5, null=True, unique=True, verbose_name='Número de Inscrição'),
        ),
    ]
