# Generated by Django 5.2.5 on 2025-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único do cupom (ex: DESCONTO10)', max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('description', models.CharField(help_text='Descrição do cupom para identificação', max_length=200, verbose_name='Descrição')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Valor fixo de desconto em reais (ex: 10.00 para R$ 10)', max_digits=10, verbose_name='Valor do Desconto (R$)')),
                ('is_active', models.BooleanField(default=True, help_text='Se o cupom está ativo e pode ser usado', verbose_name='Ativo')),
                ('valid_from', models.DateTimeField(help_text='Data/hora de início da validade', verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(help_text='Data/hora de fim da validade', verbose_name='Válido até')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Número máximo de vezes que pode ser usado (deixe vazio para ilimitado)', null=True, verbose_name='Limite de Uso')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes o cupom já foi usado', verbose_name='Vezes Usado')),
                ('valid_for_kids', models.BooleanField(default=True, help_text='Se o cupom pode ser usado na modalidade Kids', verbose_name='Válido para Kids')),
                ('valid_for_adult', models.BooleanField(default=True, help_text='Se o cupom pode ser usado nas modalidades adulto (corrida/caminhada)', verbose_name='Válido para Adulto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='raceregistration',
            name='registration_email_sent',
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Cupom Aplicado'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo de desconto aplicado em reais', max_digits=10, null=True, verbose_name='Valor do Desconto (R$)'),
        ),
    ]
