# Generated by Django 5.2.5 on 2025-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceregistration',
            name='registration_email_sent',
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='abacatepay_pix_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do PIX no AbacatePay'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Cupom Aplicado'),
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo de desconto aplicado em reais', max_digits=10, null=True, verbose_name='Valor do Desconto (R$)'),
        ),
    ]
