version: "3.9"

services:
  # Backend Django em modo desenvolvimento
  backend:
    image: python:3.12-slim
    container_name: admooving_backend_dev
    working_dir: /app
    command: >
      bash -c "
        apt-get update && apt-get install -y build-essential &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - backend_cache:/root/.cache/pip
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=True
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Frontend Vite em modo desenvolvimento
  frontend:
    image: node:20-alpine
    container_name: admooving_frontend_dev
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 8080
      "
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "8080:8080"  # Usando porta 8080 como configurado no vite.config.ts
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  # Cache do pip para acelerar reinstalações
  backend_cache:
    driver: local
    
  # node_modules para evitar conflitos entre host e container
  frontend_node_modules:
    driver: local

networks:
  default:
    name: admooving_dev_network
