version: "3.9"

services:
  # Backend Django em modo desenvolvimento
  backend:
    image: python:3.12-slim
    container_name: admooving_backend_dev
    working_dir: /app
    command: >
      bash -c "
        apt-get update && apt-get install -y build-essential &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/app
      - backend_cache:/root/.cache/pip
    env_file:
      - ./.env
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=True
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=${DB_ENGINE:-postgres}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db

  # Frontend Vite em modo desenvolvimento
  frontend:
    image: node:20-alpine
    container_name: admooving_frontend_dev
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 8080
      "
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "8080:8080"  # Usando porta 8080 como configurado no vite.config.ts
    depends_on:
      - backend
    restart: unless-stopped

  # PostgreSQL para desenvolvimento
  db:
    image: postgres:15
    container_name: admooving_db_dev
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  # Cache do pip para acelerar reinstalações
  backend_cache:
    driver: local
    
  # node_modules para evitar conflitos entre host e container
  frontend_node_modules:
    driver: local
  pg_data_dev:
    driver: local

networks:
  default:
    name: admooving_dev_network
