name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Deploy (apenas na branch main)
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        
        # Configurar SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
        # Deploy na VPS
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd /home/deploy/Ad-mooving &&
          git pull origin main &&
          cd backend && chmod +x deploy.sh && cd .. &&
          ./backend/deploy.sh production
        "
        
        echo "✅ Deployment completed!"